-- esquema relacional del portfolio. ejecutar completo en mariadb 10.6+.
CREATE DATABASE IF NOT EXISTS sara_portfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sara_portfolio;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, first_login BOOLEAN NOT NULL DEFAULT TRUE, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE site_settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(80) NOT NULL UNIQUE, setting_value TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE skill_categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0);
CREATE TABLE projects (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE, description TEXT NOT NULL, project_date DATE NULL, image_path VARCHAR(500) NULL, demo_url VARCHAR(500) NULL, github_url VARCHAR(500) NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));
CREATE TABLE technologies (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, icon VARCHAR(80) NULL);
CREATE TABLE project_technologies (project_id INT UNSIGNED NOT NULL, technology_id INT UNSIGNED NOT NULL, PRIMARY KEY(project_id,technology_id), FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(technology_id) REFERENCES technologies(id) ON DELETE RESTRICT);
CREATE TABLE skills (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, category_id INT UNSIGNED NOT NULL, level TINYINT UNSIGNED NULL CHECK(level BETWEEN 1 AND 100), icon VARCHAR(80) NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES skill_categories(id) ON DELETE RESTRICT, INDEX(category_id,active,sort_order));
CREATE TABLE education (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, institution VARCHAR(180) NOT NULL, start_date DATE NULL, end_date DATE NULL, description TEXT NULL, type VARCHAR(40) NOT NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));
CREATE TABLE timeline_events (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, year SMALLINT UNSIGNED NOT NULL, title VARCHAR(180) NOT NULL, description TEXT NULL, type VARCHAR(40) NOT NULL DEFAULT 'formación', sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));
CREATE TABLE photography (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, description TEXT NULL, image_path VARCHAR(500) NOT NULL, alt_text VARCHAR(240) NOT NULL, category VARCHAR(80) NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));
CREATE TABLE learning_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(120) NOT NULL, description TEXT NULL, icon VARCHAR(80) NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));
CREATE TABLE objectives (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, text VARCHAR(300) NOT NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));
CREATE TABLE social_links (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, label VARCHAR(80) NOT NULL, url VARCHAR(500) NOT NULL, icon VARCHAR(50) NULL, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(active,sort_order));

-- contraseña inicial: cambiar-esta-clave-2026. el primer acceso obliga a reemplazarla.
-- el hash bcrypt evita guardar la contraseña en texto plano.
INSERT INTO users(email,password_hash,first_login) VALUES ('sarawillerslohr08@gmail.com','$2a$10$eVX268.L8w6N0xNIZ/SHCOLuVo5x2fwBBIG/WTfgHq3N/24wHQeaS',TRUE);
INSERT INTO site_settings(setting_key,setting_value) VALUES
('hero_greeting','hola, soy sara 👋'),('hero_title','desarrollo web & fotografía'),('hero_text','me interesa crear soluciones digitales combinando desarrollo web, tecnología y creatividad.'),('about_title','un poco sobre mí'),('about_text','desde que comencé la orientación informática me interesó entender cómo funcionan las herramientas que utilizamos todos los días y cómo la tecnología puede utilizarse para resolver problemas reales.'),('contact_email','sarawillerslohr08@gmail.com');
INSERT INTO skill_categories(name,sort_order) VALUES ('desarrollo',1),('programación',2),('bases de datos',3),('sistemas y redes',4),('herramientas',5);
INSERT INTO skills(name,category_id,sort_order) VALUES ('typescript',1,1),('react',1,2),('node.js',1,3),('javascript',2,1),('html',2,2),('css',2,3),('sql',3,1),('mariadb',3,2),('supabase',3,3),('linux',4,1),('tcp/ip',4,2),('git',5,1),('github',5,2),('canva',5,3);
INSERT INTO projects(title,slug,description,sort_order) VALUES ('proyecto profesionalizante — intranet empresarial','intranet-empresarial','desarrollo realizado junto a mi compañera agustina banegas para una empresa local. el objetivo fue centralizar información y digitalizar distintos procesos internos mediante una plataforma web.',1),('prácticas de redes informáticas','practicas-redes','prácticas de redes con acl, ip, ubuntu server y tcp/ip.',2),('portfolio y proyectos web','portfolio-web','proyectos donde exploro desarrollo web, diseño y fotografía.',3);
INSERT INTO education(title,institution,start_date,end_date,description,type,sort_order) VALUES ('tecnicatura en informática personal y profesional','escuela de educación secundaria técnica n.º 5 "amancio williams"','2020-03-01','2026-12-01','formación técnica orientada a programación, redes, sistemas y desarrollo web.','tecnicatura',1),('desarrollo web — chicas programadoras / globant','chicas programadoras / globant','2022-03-01','2022-06-01',NULL,'curso',2),('introducción al diseño gráfico','plataforma de aprendizaje virtual','2026-02-26',NULL,NULL,'curso',3),('elevating your english: communicating as a leader','santander open academy','2026-03-09',NULL,NULL,'curso',4);
INSERT INTO timeline_events(year,title,description,sort_order) VALUES (2020,'inicio de la tecnicatura','comienzo de la orientación informática.',1),(2022,'desarrollo web','chicas programadoras / globant.',2),(2024,'primeros proyectos completos','exploración de desarrollo web.',3),(2025,'redes y servidores','prácticas de infraestructura.',4),(2026,'último año de la tecnicatura','formación y cursos complementarios.',5);
INSERT INTO photography(title,image_path,alt_text,category,sort_order) VALUES ('luz y composición','/IMG_6512.JPG','fotografía de sara willers','fotografía',1),('mirada urbana','/IMG_6266.JPG','fotografía urbana de sara willers','fotografía',2),('detalle','/IMG_6140.JPG','fotografía de detalle de sara willers','fotografía',3),('color','/IMG_5646.JPG','fotografía colorida de sara willers','fotografía',4),('atmósfera','/IMG_3737_copy.JPG','fotografía de sara willers','fotografía',5);
INSERT INTO learning_items(title,sort_order) VALUES ('desarrollo web',1),('bases de datos',2),('programación',3),('redes',4),('sistemas operativos',5),('diseño',6),('soporte técnico',7),('seguridad informática',8);
INSERT INTO objectives(text,sort_order) VALUES ('especializarme progresivamente en frontend',1),('mejorar mis conocimientos de javascript y frameworks',2),('continuar explorando diseño y fotografía',3),('adquirir experiencia profesional',4),('participar en proyectos tecnológicos reales',5);
INSERT INTO social_links(label,url,icon,sort_order) VALUES ('linkedin','https://www.linkedin.com/in/sara-willers-l%C3%B6hr-2472803ba/','in',1),('email','mailto:sarawillerslohr08@gmail.com','@',2);
