import { type FormEvent, useEffect, useState } from 'react';
import { ConfirmModal } from '../components/ui';
import type { Item } from '../types';

const sections=[['projects','proyectos'],['photography','fotografía'],['education','formación'],['skills','habilidades'],['timeline_events','recorrido'],['learning_items','aprendizajes'],['objectives','objetivos'],['social_links','contacto'],['site_settings','configuración']] as const;
const api=async(path:string,token?:string,options:RequestInit={})=>{const response=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}),...options.headers}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||'No se pudo completar la operación.')}return response.status===204?null:response.json()};
export function AdminPage(){const [token,setToken]=useState(()=>sessionStorage.getItem('portfolio_token')||'');const [firstLogin,setFirstLogin]=useState(false);const [section,setSection]=useState<typeof sections[number][0]>('projects');const [rows,setRows]=useState<Item[]>([]);const [message,setMessage]=useState('');const [selected,setSelected]=useState<Item|null>(null);const [deleting,setDeleting]=useState<Item|null>(null);const [email,setEmail]=useState('');const [password,setPassword]=useState('');
const load=async()=>{if(!token)return;try{setRows(await api(`/admin/${section}`,token));setSelected(null)}catch(e){setMessage(e instanceof Error?e.message:'Error inesperado')}};useEffect(()=>{load()},[section,token]);
const login=async(e:FormEvent)=>{e.preventDefault();try{const result=await api('/admin/login',undefined,{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('portfolio_token',result.token);setToken(result.token);setFirstLogin(result.firstLogin)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo ingresar')}};
const changePassword=async(e:FormEvent)=>{e.preventDefault();try{await api('/admin/change-password',token,{method:'POST',body:JSON.stringify({password})});setFirstLogin(false);setPassword('');setMessage('Contraseña actualizada. Ya podés editar el portfolio.')}catch(e){setMessage(e instanceof Error?e.message:'Error')}};
const save=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;try{const {id,...payload}=selected;await api(`/admin/${section}${id?`/${id}`:''}`,token,{method:id?'PUT':'POST',body:JSON.stringify(payload)});setMessage('Cambios guardados.');load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar')}};
const remove=async()=>{if(!deleting)return;try{await api(`/admin/${section}/${deleting.id}`,token,{method:'DELETE'});setDeleting(null);setMessage('Elemento eliminado.');load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo eliminar')}};
const uploadImage=async(file:File)=>{const form=new FormData();form.append('image',file);try{const response=await fetch('/api/admin/upload',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});const body=await response.json();if(!response.ok)throw new Error(body.message);setSelected(current=>current?{...current,image_path:body.path}:current);setMessage('Imagen cargada. Guardá el formulario para asociarla.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo cargar la imagen')}};
if(!token)return <main className="admin-login"><div className="login-card"><a href="/" className="brand">sara<span>wl.</span></a><p className="eyebrow">administración</p><h1>bienvenida de nuevo</h1><p>Ingresá para gestionar el contenido de tu portfolio.</p><form onSubmit={login}><label>email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label><button className="button">entrar al dashboard →</button></form>{message&&<p className="notice error">{message}</p>}</div></main>;
if(firstLogin)return <main className="admin-login"><div className="login-card"><p className="eyebrow">seguridad</p><h1>cambiá tu contraseña</h1><p>Es tu primer acceso: elegí una nueva contraseña de al menos 10 caracteres.</p><form onSubmit={changePassword}><label>nueva contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} required/></label><button className="button">guardar y continuar</button></form>{message&&<p className="notice error">{message}</p>}</div></main>;
return <main className="admin"><aside><a href="/" className="brand">sara<span>wl.</span></a><p>cms del portfolio</p>{sections.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}<button className="logout" onClick={()=>{sessionStorage.removeItem('portfolio_token');setToken('')}}>cerrar sesión</button></aside><section className="admin-content"><header><div><p className="eyebrow">gestión de contenido</p><h1>{sections.find(x=>x[0]===section)?.[1]}</h1></div><button className="button" onClick={()=>setSelected(defaultItem(section))}>+ crear</button></header>{message&&<p className="notice">{message}</p>}<div className="admin-grid"><div className="admin-list">{rows.map(row=><article key={row.id} className={selected?.id===row.id?'selected':''}><div><strong>{String(row.title||row.name||row.text||row.setting_key||row.label)}</strong><small>{row.active===0?'inactivo':'visible'}</small></div><button onClick={()=>setSelected(row)}>editar</button><button className="delete" onClick={()=>setDeleting(row)}>eliminar</button></article>)}{!rows.length&&<p className="empty">Todavía no hay elementos en esta sección.</p>}</div>{selected&&<form className="editor" onSubmit={save}><h2>{selected.id?'editar':'crear'} elemento</h2>{Object.entries(selected).filter(([key])=>!['id','created_at','updated_at'].includes(key)).map(([key,value])=><label key={key}>{key.replaceAll('_',' ')}{key==='image_path'?<><input value={String(value??'')} onChange={e=>setSelected({...selected,[key]:e.target.value})}/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)uploadImage(file)}}/></>:typeof value==='number'&&key==='active'?<select value={String(value)} onChange={e=>setSelected({...selected,[key]:Number(e.target.value)})}><option value="1">activo</option><option value="0">inactivo</option></select>:<input value={String(value??'')} onChange={e=>setSelected({...selected,[key]:key==='sort_order'?Number(e.target.value):e.target.value})} />}</label>)}<div><button className="button">guardar</button><button type="button" className="button ghost" onClick={()=>setSelected(null)}>cancelar</button></div></form>}</div></section><ConfirmModal open={Boolean(deleting)} title={`¿querés eliminar “${String(deleting?.title||deleting?.name||deleting?.text||deleting?.setting_key||'este elemento')}”?`} onCancel={()=>setDeleting(null)} onConfirm={remove}/></main>}
function defaultItem(section:string):Item { const base={active:1,sort_order:99}; const presets:Record<string,Item>={projects:{...base,title:'nuevo proyecto',slug:`proyecto-${Date.now()}`,description:'',image_path:''},photography:{...base,title:'nueva fotografía',description:'',image_path:'',alt_text:'',category:'fotografía'},education:{...base,title:'nueva formación',institution:'',start_date:'',end_date:'',description:'',type:'curso'},skills:{...base,name:'nueva habilidad',category_id:1,level:0,icon:''},timeline_events:{...base,year:2026,title:'nuevo evento',description:'',type:'formación'},learning_items:{...base,title:'nuevo aprendizaje',description:'',icon:''},objectives:{...base,text:'nuevo objetivo'},social_links:{...base,label:'nuevo enlace',url:'https://',icon:''},site_settings:{setting_key:'nueva_configuración',setting_value:''}}; return presets[section]; }
