import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { PhotoCarousel } from '../components/PhotoCarousel';
import { Reveal, SectionTitle } from '../components/ui';
import { usePortfolio, useTheme } from '../hooks';
import type { Item } from '../types';

const nav=[['inicio','inicio'],['sobre-mi','sobre mí'],['fotografia','fotografía'],['proyectos','proyectos'],['formacion','formación'],['habilidades','habilidades'],['recorrido','recorrido'],['objetivos','objetivos'],['contacto','contacto']];
const text=(item:Item,key:string)=>String(item[key]||'');
export function PortfolioPage(){const {data,error}=usePortfolio();const {theme,toggle}=useTheme();const [menu,setMenu]=useState(false);const [top,setTop]=useState(false);useEffect(()=>{const handler=()=>setTop(scrollY>500);addEventListener('scroll',handler);handler();return()=>removeEventListener('scroll',handler)},[]);if(error)return <main className="status"><h1>portfolio de sara willers löhr</h1><p>{error}</p></main>;if(!data)return <main className="status"><div className="loader"/><p>cargando portfolio…</p></main>;const s=data.settings;return <><header className="nav"><a href="#inicio" className="brand">sara<span>wl.</span></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Abrir navegación">☰</button><nav className={menu?'open':''}>{nav.map(([id,label])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}</a>)}<button className="theme" onClick={toggle} aria-label="Cambiar modo de color">{theme==='light'?'◐':'☼'}</button></nav></header><main>
<section id="inicio" className="hero"><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>mar del plata · argentina</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.1}}>{s.hero_greeting}<br/><em>{s.Subtitulo || 'Estudiante de informática'}</em></motion.h1><motion.p className="lead" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}}>{s.hero_text}</motion.p><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.4}}><a className="button" href="#proyectos">ver mis proyectos ↗</a><a className="button ghost" href="#sobre-mi">conocerme</a></motion.div></div><motion.div className="hero-photo" initial={{rotate:4,opacity:0}} animate={{rotate:2,opacity:1}} transition={{delay:.15}}><img src="/foto-perfil.jpeg" alt="Sara Willers Löhr"/><span>estudiante · creativa · tech</span></motion.div></section>
<section id="sobre-mi" className="about section"><div><SectionTitle eyebrow="acerca de mí" title={s.about_title}><p>{s.about_text}</p><p>Durante la tecnicatura adquirí conocimientos en programación, desarrollo web, bases de datos, redes informáticas, sistemas operativos y mantenimiento de equipos.</p><p>También me interesan el diseño, la fotografía y la posibilidad de combinar tecnología y creatividad en proyectos digitales.</p></SectionTitle></div><Reveal delay={.15}><img className="polaroid" src="/IMG_1255.JPG" alt="Fotografía tomada por Sara"/></Reveal></section>
<section id="fotografia" className="section photo-section"><SectionTitle eyebrow="mi mirada detrás de la cámara" title="fotografía"><p>La fotografía es uno de los ámbitos creativos que más me interesa explorar. Me gusta observar detalles, experimentar con diferentes composiciones y utilizar la imagen como una forma de comunicar ideas.</p></SectionTitle><PhotoCarousel photos={data.photos}/></section>
<section id="proyectos" className="section"><SectionTitle eyebrow="desarrollo web" title="proyectos destacados"/><div className="project-grid">{data.projects.map((project,i)=><Reveal key={project.id} delay={i*.08}><article className="project-card"><span>0{i+1} / proyecto</span><h3>{project.title}</h3><p>{project.description}</p><div className="tags">react · node.js · aprendizaje continuo</div>{project.github_url&&<a href={project.github_url}>ver código ↗</a>}</article></Reveal>)}</div></section>
<section id="formacion" className="section education"><SectionTitle eyebrow="aprendizaje constante" title="mi formación"/><div>{data.education.map(item=><Reveal key={item.id}><article className="education-row"><small>{text(item,'type')}</small><div><h3>{text(item,'title')}</h3><p>{text(item,'institution')}</p></div><p>{text(item,'start_date').slice(0,4)} — {text(item,'end_date').slice(0,4)||'actualidad'}</p></article></Reveal>)}</div></section>
<section id="habilidades" className="section"><SectionTitle eyebrow="herramientas que uso" title="stack & habilidades"/><div className="skills">{data.skills.map(item=><span key={item.id}>{text(item,'name')}</span>)}</div></section>
<section id="recorrido" className="section timeline"><SectionTitle eyebrow="paso a paso" title="mi recorrido en la informática"/>{data.timeline.map(item=><Reveal key={item.id}><article><time>{text(item,'year')}</time><div><h3>{text(item,'title')}</h3><p>{text(item,'description')}</p></div></article></Reveal>)}</section>
<section className="section learn"><SectionTitle eyebrow="en construcción" title="lo que aprendí"/><div>{data.learning.map(item=><Reveal key={item.id}><article>{text(item,'title')}<span>↗</span></article></Reveal>)}</div></section>
<section id="objetivos" className="section goals"><SectionTitle eyebrow="próximo capítulo" title="hacia dónde quiero seguir"><p>Actualmente mi objetivo es continuar aprendiendo y adquirir experiencia en el área tecnológica, especialmente en desarrollo web y frontend.</p></SectionTitle><ul>{data.objectives.map(item=><li key={item.id}>{text(item,'text')}</li>)}</ul></section>
<section id="contacto" className="contact"><Reveal><p className="eyebrow">conectemos</p><h2>¿hablamos?</h2><a href={`mailto:${s.contact_email}`}>{s.contact_email}</a><div>{data.links.map(link=><a key={link.id} href={text(link,'url')} target="_blank" rel="noreferrer">{text(link,'label')} ↗</a>)}</div></Reveal></section></main><footer><span>sara willers löhr · estudiante de informática · desarrollo web · fotografía</span><span>© 2026</span></footer>{top&&<button className="back-top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Volver arriba">↑</button>}</>}
